name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: install
      working-directory: ./E1
      run: make install
    - name: compile files
      working-directory: ./E1
      run: make compile
    - name: E1
      id: e1
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: E1
        setup-command: ''
        command: "./E1/e1"
        input: 7012 * 12341 + 8090
        expected-output: |-
          categoria do token: 1, constante numérica: 7012
          categoria do token: 4
          categoria do token: 1, constante numérica: 12341
          categoria do token: 2
          categoria do token: 1, constante numérica: 8090
        comparison-method: exact
        timeout: 5
        max-score: 10
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        E1_RESULTS: "${{steps.e1.outputs.result}}"
      with:
        runners: e1
